openapi: "3.0.0"
info:
  version: 1.0.0
  title: todoapp
  description: A todo API that uses OpenAPI 3.0 specification.
  contact:
    name: Richard Severich
    email: richard.severich@gmail.com
servers:
  - url: http://localhost:5001/api/v1/
paths:
  /user:
    $ref: "./services/service-user-id.yaml"
  /user/:id:
    $ref: "./services/service-user-id.yaml"
  /project:
    $ref: "./services/service-project-id.yaml"
  /project/:id:
    $ref: "./services/service-project-id.yaml"
  /task:
    $ref: "./services/service-task-id.yaml"
  /task/:id:
    $ref: "./services/service-task-id.yaml"

components:
  schemas:
    User:
      $ref: "./schemas/schema-user.yaml#/User"
    Project:
      $ref: "./schemas/schema-project.yaml#/Project"
    Task:
      $ref: "./schemas/schema-task.yaml#/Task"
    Message:
      $ref: "./schemas/schema-message.yaml#/Message"
