image: node:14.15.0

cache:
  paths:
    - node_modules/

stages:
  - build
  - quality

build:
  stage: build
  script:
    - npm install
    - npm build
    - echo "Build successfully!"

lint:
  stage: quality
  script:
    - npm install
    - npm run lint .
    
test:
  stage: quality
  script:
    - npm install
    - npm test -- --coverage
    - echo "Test successfully!"

